version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    env_file:
      - .env
    ports:
      - '5432:5432'
